import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        heading: ["Montserrat", "system-ui", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        spark: {
          nav: "hsl(var(--spark-nav))",
          "nav-foreground": "hsl(var(--spark-nav-foreground))",
          "sidebar-bg": "hsl(var(--spark-sidebar-bg))",
          "sidebar-foreground": "hsl(var(--spark-sidebar-foreground))",
          "card-border": "hsl(var(--spark-card-border))",
          "accent-purple": "hsl(var(--spark-accent-purple))",
          "status-blue": "hsl(var(--spark-status-blue))",
        },
        // Custom palette
        "neon-pink": {
          DEFAULT: "hsl(var(--neon-pink))",
          50: "#e6f0ff",
          100: "#b3d4ff",
          200: "#80b8ff",
          300: "#4d9cff",
          400: "#0066FF",
          500: "#0052cc",
          600: "#003d99",
          700: "#002966",
          800: "#001433",
        },
        "indigo-bloom": {
          DEFAULT: "hsl(var(--indigo-bloom))",
          50: "#e8f0fa",
          100: "#c1d6ef",
          200: "#9abce4",
          300: "#73a2d9",
          400: "#4A90D9",
          500: "#3a73ae",
          600: "#2b5682",
          700: "#1d3a57",
          800: "#0e1d2b",
        },
        "vivid-royal": {
          DEFAULT: "hsl(var(--vivid-royal))",
          50: "#e0ecff",
          100: "#b3ccff",
          200: "#80aaff",
          300: "#4d88ff",
          400: "#0052cc",
          500: "#003da3",
          600: "#002e7a",
          700: "#001f52",
          800: "#000f29",
        },
        "electric-sapphire": {
          DEFAULT: "hsl(var(--electric-sapphire))",
          50: "#e8f0fa",
          100: "#c1d6ef",
          200: "#9abce4",
          300: "#73a2d9",
          400: "#4A90D9",
          500: "#3a73ae",
          600: "#2b5682",
          700: "#1d3a57",
          800: "#0e1d2b",
        },
        "sky-aqua": {
          DEFAULT: "hsl(var(--sky-aqua))",
          50: "#e0f7ff",
          100: "#b3ecff",
          200: "#80e0ff",
          300: "#4dd5ff",
          400: "#00C2FF",
          500: "#009bcc",
          600: "#007499",
          700: "#004d66",
          800: "#002733",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 20px hsl(216 100% 50% / 0.2)" },
          "50%": { boxShadow: "0 0 40px hsl(216 100% 50% / 0.4)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "float": "float 6s ease-in-out infinite",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
